"""empty message

Revision ID: 1970cc814fe0
Revises: 1a72775ca644
Create Date: 2022-10-18 06:51:59.820611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1970cc814fe0'
down_revision = '1a72775ca644'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedbacks', sa.Column('submission_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedbacks', 'submission_time')
    # ### end Alembic commands ###
